require("user.options")
require("user.mappings")
require("user.plugs")
require("user.theme")

require("user.plugins.navigator")
require("user.plugins.which-key")
require("user.plugins.telescope")
require("user.plugins.which-key")
require("user.plugins.nvim-tree")
require("user.plugins.null-ls")
require("user.plugins.lualine")
require("user.plugins.bufferline")
require("user.plugins.fugitive")
require("user.plugins.trouble")
