-- Core
require("user.options")
require("user.commands")
require("user.mappings")
require("user.plugs")
require("user.theme")
-- Plugins Core
require("user.plugins.alpha")
require("user.plugins.navigator")
require("user.plugins.which-key")
require("user.plugins.telescope")
require("user.plugins.which-key")
require("user.plugins.nvim-tree")
require("user.plugins.lsp")
require("user.plugins.lualine")
require("user.plugins.bufferline")
require("user.plugins.fugitive")
require("user.plugins.trouble")
require("user.plugins.tree-sitter")
-- Plugins Additional
require("user.plugins.harpoon")
-- require("user.plugins.shade")
