#!/bin/bash

DOTFILES=$HOME/dotfiles/
# Bash {{{

ln -s $HOME/dotfiles/bash/.bashrc $HOME
ln -s $HOME/dotfiles/bash/.bash_logout $HOME
# }}}

# Git {{{

ln -s $HOME/dotfiles/.gitconfig $HOME
# }}}

# Tmux {{{

ln -s $HOME/dotfiles/tmux/.tmux.conf $HOME
# }}}

# Vim {{{

ln -s $HOME/dotfiles/vim/.vim $HOME
ln -s $HOME/dotfiles/vim/.nvimrc $HOME
# }}}

# Zsh {{{

ln -s $HOME/dotfiles/zsh/.zshrc $HOME/zsh/.zhsrc
ln -s $HOME/dotfiles/zsh/.zlogin $HOME/.zlogin
ln -s $HOME/dotfiles/zsh/.zlogout $HOME/.zlogout
ln -s $HOME/dotfiles/zsh/.zsh_private $HOME/.zsh
ln -s $HOME/dotfiles/zsh/.agnoster.zsh $HOME/.zsh
ln -s $HOME/dotfiles/zsh/.fzf.zsh $HOME/.zsh
# }}}

# Ctags {{{

ln -s $HOME/dotfiles/ctags/.ctags $HOME
# }}}

# sqliterc {{{

ln -s $HOME/dotfiles/etc/.sqliterc $HOME
# }}}

# bins {{{

ln -s $DOTFILES/bin/utils/genpasswd $HOME/.local/bin
# }}}
