#!/bin/bash

DOTFILES=$HOME/dotfiles/
ZMAIN="$HOME/.zsh"
# Bash {{{

ln -s $HOME/dotfiles/bash/.bashrc $HOME
ln -s $HOME/dotfiles/bash/.bash_logout $HOME
# }}}

# bat {{{

ln -s $DOTFILES/bat/bat.conf $HOME/.config
# }}}

# Git {{{

ln -s $HOME/dotfiles/.gitconfig $HOME
# }}}

# Tmux {{{

ln -s $HOME/dotfiles/tmux/.tmux.conf $HOME
# }}}

# Vim {{{

ln -s $HOME/dotfiles/vim/.vim $HOME
ln -s $HOME/dotfiles/vim/.nvimrc $HOME
# }}}

# Zsh {{{

# lsd
mkdir -p $HOME/.config/lsd
ln -sf $HOME/dotfiles/.config/lsd/config.yaml $HOME/.config/lsd/config.yaml
# }}}

# Ctags {{{

ln -s $HOME/dotfiles/ctags/.ctags $HOME
# }}}

# sqliterc {{{

ln -s $HOME/dotfiles/etc/.sqliterc $HOME
# }}}

# kubernetes {{{

ln -s ${DOTFILES}/kube/kind.yaml ${HOME}/.kube
# }}}

# bins {{{

ln -s $DOTFILES/bin/utils/genpasswd $HOME/.local/bin
# }}}

# node {{{

ln -s $DOTFILES/node/.npmrc $HOME/.npmrc
# }}}
