font:
  normal:
    family: &ubuntu_family 'Ubuntu Mono'                        # Default
      # family: &ubuntu_family 'Ubuntu Mono derivative Powerline'   # Powerline
    # family: &ubuntu_family 'UbuntuMono Nerd Font Mono'          # Nerd font
    # family: &ubuntu_family 'SF Mono Powerline'
    style: Regular
  bold:
    family: *ubuntu_family
    style: Bold
  italic:
    family: *ubuntu_family
    style: Italic
  bold_italic:
    family: *ubuntu_family
    style: Bold Italic
  # size: 11.0 # SF Mono
  size: 12.0
