font:
  normal:
    # family: &ubuntu_family 'Ubuntu Mono'                        # Default
    family: &ubuntu_family 'UbuntuMono Nerd Font Mono'          # Nerd font
    # family: &ubuntu_family 'Ubuntu Mono derivative Powerline'   # Powerline
    # family: &ubuntu_family 'SFMono Nerd Font'                   # SF Mono MacOS
    style: Regular
  bold:
    family: *ubuntu_family
    style: Bold
  italic:
    family: *ubuntu_family
    style: Italic
  bold_italic:
    family: *ubuntu_family
    style: Bold Italic
  # size: 11.0 # SF Mono MacOS
  size: 12.0

window:
  startup_mode: Fullscreen
  dynamic_title: true
  padding:
    x: 2
    y: 0
