font:
  normal:
    family: &sf_family 'SF Mono'
    # family: &sf_family 'SFMono Nerd Font'
    style: Regular
  bold:
    family: *sf_family
    style: Bold
  italic:
    family: *sf_family
    style: Italic
  bold_italic:
    family: *sf_family
    style: Bold Italic
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0
  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true
  size: 12
